{{- if or .Values.secret.mongodbUri .Values.env.mongodbUri .Values.secret.jwtSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "yms-appt-service.fullname" . }}
  labels:
    {{- include "yms-appt-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if or .Values.secret.mongodbUri .Values.env.mongodbUri }}
  MONGODB_URI: {{ default .Values.env.mongodbUri .Values.secret.mongodbUri | quote }}
  {{- end }}
  {{- if .Values.secret.jwtSecret }}
  JWT_SECRET: {{ .Values.secret.jwtSecret | quote }}
  {{- end }}
{{- end -}}

